trigger: none

pool:
  name: NetCore-Public
  demands: ImageOverride -equals 1es-windows-2022-open

stages:
- stage: pull
  dependsOn: []
  displayName: Pull
  jobs:
  - job: Pull
    steps:
    - powershell: |
        docker pull dotnetdhmirror-f8bzbjakh8cga6ab.azurecr.io/registry:2
      displayName: Pull image
